# Generated by Django 3.1.7 on 2022-06-07 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order',
            new_name='quantity',
        ),
    ]
