# Generated by Django 3.1.7 on 2022-06-12 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20220612_1757'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='out_of_stock',
            new_name='outOfStock',
        ),
    ]
