# Generated by Django 3.1.7 on 2022-06-12 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20220612_1759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='outOfStock',
        ),
    ]
