# Generated by Django 3.1.7 on 2022-06-12 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_remove_order_outofstock'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='out',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
