# Generated by Django 3.1.7 on 2022-06-12 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_order_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermessage',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.order'),
        ),
    ]
