# Generated by Django 3.1.7 on 2022-06-12 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_ordermessage_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermessage',
            name='order',
        ),
    ]
