# Generated by Django 3.1.7 on 2022-06-07 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20220607_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='p_default.jpg', upload_to='Profile_Images'),
        ),
    ]
